### ISSUE TITLE
Mermaid SVG 404

### ISSUE THREAD

**Issue by OliverCole** [rhanekom/gatsby-remark-draw#1]
Running the demo site locally, all mermaid SVGs are 404. This is in multiple browsers, on Windows.

1. `git clone https://github.com/rhanekom/gatsby-remark-draw-demo.git`
1. `cd gatsby-remark-draw-demo`
1. `yarn`
1. `npm run develop`
1. SVG files are correct in the `public` directory
1. Load up http://localhost:8000/mermaid/

Get this - note the `%5c` at the start of the URL:

![image](https://user-images.githubusercontent.com/6171713/52668198-d1599c00-2f0a-11e9-9f3b-22cc9a6f0333.png)

**Comment by OliverCole** [comment]
Works on Linux.

**Comment by rhanekom** [comment]
Thank you for the investigation and the fix Oliver!  Will merge and publish shortly.

**Comment by OliverCole** [comment]
Just following up - keen to get this released soon? :)

**Comment by rhanekom** [comment]
Merged and pushed as v1.0.16.  Thanks again ;)
